export const Data = [
  {
    orden: "001",
    fecha: "2024-05-28",
    programado: 100,
    consumido: 50,
    restante: 50,
    merma: "5%",
    progreso: "50%",
    estado: "En curso",
    expandida: {
      tejido: "Algodón",
      ancho: "1.5m",
      hilanderia: "Hilandera S.A.",
      programado: 100,
      consumido: 50,
      restante: 50,
      rollos: 10,
      peso: 50,
      estado: "En curso",
    },
  },
  {
    orden: "002",
    fecha: "2024-05-27",
    programado: 200,
    consumido: 180,
    restante: 20,
    merma: "3%",
    progreso: "90%",
    estado: "Listo",
    expandida: {
      tejido: "Poliéster",
      ancho: "1.2m",
      hilanderia: "Hilandería S.A.",
      programado: 200,
      consumido: 180,
      restante: 20,
      rollos: 15,
      peso: 180,
      estado: "Listo",
    },
  },
  {
    orden: "002",
    fecha: "2024-05-27",
    programado: 200,
    consumido: 180,
    restante: 20,
    merma: "3%",
    progreso: "90%",
    estado: "Listo",
    expandida: {
      tejido: "Poliéster",
      ancho: "1.2m",
      hilanderia: "Hilandería S.A.",
      programado: 200,
      consumido: 180,
      restante: 20,
      rollos: 15,
      peso: 180,
      estado: "Listo",
    },
  },
  
];